<a href="https://colab.research.google.com/github/salgudekomal945-ops/my-colab-work/blob/main/operations_on_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a = np.array([[1,2,3,],
             [4,5,6]])
#append method
np.append(a,[7,8,9])
np.append(a,[[7,8,9]],axis=0)
np.append(a,[[5],[8]],axis=1)

array([[1, 2, 3, 5],
       [4, 5, 6, 8]])

In [11]:
a = np.array([[1,2],
              [3,4],
              [5,6]])
#insert method
np.insert(a,3,[7,8])
np.insert(a,1,[7,8],axis=0)
np.insert(a,2,[7,8,9],axis=1)


array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [22]:
a = np.array([[1,2,3,12],
              [9,5,6,11],
              [8,4,10,7]])
#delete method
np.delete(a,1)
np.delete(a,1,axis=0)
np.delete(a,1,axis= 1)

array([[ 1,  3, 12],
       [ 9,  6, 11],
       [ 8, 10,  7]])

In [13]:
np.ndim(a)

2

In [25]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a,b)
print(np.ndim(a),np.ndim(b))

[1 2 3] [4 5 6]
1 1


In [30]:
#Hstack
result = np.hstack((a,b))
print(result, np.ndim(result))

[1 2 3 4 5 6] 1


In [34]:
#Vstack
result = np.vstack((a,b))
print(result,np.ndim(result))

[[1 2 3]
 [4 5 6]] 2


In [42]:
#concatenate
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[7,8,9],
                 [10,11,12]])
new = np.concatenate((arr1,arr2),axis=0)  #adding rows
print(new)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [40]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[7,8,9],
                 [10,11,12]])
new = np.concatenate((arr1,arr2),axis=1)  #adding columns
print(new)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
