<a href="https://colab.research.google.com/github/salgudekomal945-ops/my-colab-work/blob/main/Reshaping(arr)_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)  #1D to 2D
newarr = arr.reshape(2,3,2) #1D to 3D
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [9]:
arr = np.array([1,2,3,4])
print(arr[1] +arr[2])         #access via index

5


In [12]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,4])     #acess 2D array

10


In [19]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])   #access 3D array
print(arr[1,1,2])
print(arr)

6
12
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
