<a href="https://colab.research.google.com/github/salgudekomal945-ops/my-colab-work/blob/main/Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a1 = np.array([1,2,3,4,5,6,7]) #1D slicing
a1[1:5]
a1[4:]
a1[:4]

array([1, 2, 3, 4])

In [6]:
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])  #2D slicing
a2[1,1:4]
a2[0:2,2]
a2[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [7]:
a3 = np.array([[[10,11,12],[13,14,15],[16,17,18]],
              [[20,21,22],[23,24,25],[26,27,28]],
              [[30,31,32],[33,34,35],[36,37,38]]])

In [8]:
a3.shape

(3, 3, 3)

In [9]:
a3[:2,1:,:2]          #3D slicing

array([[[13, 14],
        [16, 17]],

       [[23, 24],
        [26, 27]]])

In [11]:
arr = np.array([1,2,3,4,5])
#copy method
copy = arr.copy()
copy[0]=42
print(arr)
print(copy)

[1 2 3 4 5]
[42  2  3  4  5]


In [12]:
#view method
view = arr.view()
view[0]=42
print(arr)
print(view)

[42  2  3  4  5]
[42  2  3  4  5]
